// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-app/internal/auth"
	"go-app/internal/channel"
	"go-app/internal/channel/repo"
	"go-app/internal/connection"
	"go-app/internal/group"
	"go-app/internal/message"
	repo2 "go-app/internal/message/repo"
	"go-app/internal/refresh-token"
	"go-app/internal/role"
	"go-app/internal/upload"
	"go-app/internal/user"
	"go-app/internal/websocket"
)

// Injectors from auth.wire.go:

func InitAuthRouterHandler() (*auth.AuthController, error) {
	iUserRepo := user.NewUserRepo()
	iRefreshTokenRepo := refreshtoken.NewRefreshTokenRepo()
	iRefreshTokenService := refreshtoken.NewRefreshTokenService(iRefreshTokenRepo)
	iRoleRepo := role.NewRoleRepo()
	iAuthService := auth.NewAuthService(iUserRepo, iRefreshTokenService, iRoleRepo)
	authController := auth.NewAuthController(iAuthService)
	return authController, nil
}

// Injectors from channel.wire.go:

func InitChannelService() (channel.IChannelService, error) {
	iChannelRepo := repo.NewChannelRepo()
	iChannelMemberRepo := repo.NewChannelMemberRepo()
	iChannelUnreadRepo := repo.NewChannelUnreadRepo()
	iUserRepo := user.NewUserRepo()
	channelIUserRepo := provideChannelUserRepo(iUserRepo)
	iConnectionRepo := conection.NewConnectionRepo()
	channelIConnectionRepo := provideChannelConnectionRepo(iConnectionRepo)
	iGroupRepo := group.NewGroupRepo()
	channelIGroupRepo := provideChannelGroupRepo(iGroupRepo)
	iMessageRepo := repo2.NewMessageRepo()
	channelIMessageRepo := provideChannelMessageRepo(iMessageRepo)
	iChannelService := channel.NewChannelService(iChannelRepo, iChannelMemberRepo, iChannelUnreadRepo, channelIUserRepo, channelIConnectionRepo, channelIGroupRepo, channelIMessageRepo)
	return iChannelService, nil
}

// Injectors from connection.wire.go:

func InitConnectionService() (conection.IConnectionService, error) {
	iUserRepo := user.NewUserRepo()
	iConnectionRepo := conection.NewConnectionRepo()
	iChannelRepo := repo.NewChannelRepo()
	iChannelMemberRepo := repo.NewChannelMemberRepo()
	iChannelUnreadRepo := repo.NewChannelUnreadRepo()
	channelIUserRepo := provideChannelUserRepo(iUserRepo)
	channelIConnectionRepo := provideChannelConnectionRepo(iConnectionRepo)
	iGroupRepo := group.NewGroupRepo()
	channelIGroupRepo := provideChannelGroupRepo(iGroupRepo)
	iMessageRepo := repo2.NewMessageRepo()
	channelIMessageRepo := provideChannelMessageRepo(iMessageRepo)
	iChannelService := channel.NewChannelService(iChannelRepo, iChannelMemberRepo, iChannelUnreadRepo, channelIUserRepo, channelIConnectionRepo, channelIGroupRepo, channelIMessageRepo)
	iConnectionService := conection.NewConnectionService(iUserRepo, iConnectionRepo, iChannelService)
	return iConnectionService, nil
}

// Injectors from group.wire.go:

func InitGroupService() (group.IGroupService, error) {
	iUserRepo := user.NewUserRepo()
	iRoleRepo := role.NewRoleRepo()
	userIRoleRepo := provideUserRoleRepo(iRoleRepo)
	iConnectionRepo := conection.NewConnectionRepo()
	iConnectionService := provideUserConnectionService(iConnectionRepo)
	iUserService := user.NewUserService(iUserRepo, userIRoleRepo, iConnectionService)
	iGroupRepo := group.NewGroupRepo()
	iChannelRepo := repo.NewChannelRepo()
	iChannelMemberRepo := repo.NewChannelMemberRepo()
	iChannelUnreadRepo := repo.NewChannelUnreadRepo()
	channelIUserRepo := provideChannelUserRepo(iUserRepo)
	channelIConnectionRepo := provideChannelConnectionRepo(iConnectionRepo)
	channelIGroupRepo := provideChannelGroupRepo(iGroupRepo)
	iMessageRepo := repo2.NewMessageRepo()
	channelIMessageRepo := provideChannelMessageRepo(iMessageRepo)
	iChannelService := channel.NewChannelService(iChannelRepo, iChannelMemberRepo, iChannelUnreadRepo, channelIUserRepo, channelIConnectionRepo, channelIGroupRepo, channelIMessageRepo)
	iGroupService := group.NewGroupService(iUserService, iGroupRepo, iChannelService)
	return iGroupService, nil
}

// Injectors from message.wire.go:

// InitMessageService khởi tạo MessageService với tất cả dependencies (không bao gồm Hub)
func InitMessageService() (message.IMessageService, error) {
	iMessageRepo := repo2.NewMessageRepo()
	iMessageOffsetRepo := repo2.NewMessageOffsetRepo()
	iMessageExtraRepo := repo2.NewMessageExtraRepo()
	iChannelRepo := repo.NewChannelRepo()
	messageIChannelRepo := provideMessageChannelRepo(iChannelRepo)
	iChannelMemberRepo := repo.NewChannelMemberRepo()
	messageIChannelMemberRepo := provideMessageChannelMemberRepo(iChannelMemberRepo)
	iMessageService := message.NewMessageService(iMessageRepo, iMessageOffsetRepo, iMessageExtraRepo, messageIChannelRepo, messageIChannelMemberRepo)
	return iMessageService, nil
}

// Injectors from refresh-token.wire.go:

func InitRefreshTokenRouterHandler() (*refreshtoken.RefreshTokenController, error) {
	iRefreshTokenRepo := refreshtoken.NewRefreshTokenRepo()
	iRefreshTokenService := refreshtoken.NewRefreshTokenService(iRefreshTokenRepo)
	refreshTokenController := refreshtoken.NewRefreshTokenController(iRefreshTokenService)
	return refreshTokenController, nil
}

// Injectors from role.wire.go:

func InitRoleRouterHandler() (*role.RoleController, error) {
	iRoleRepo := role.NewRoleRepo()
	iRoleService := role.NewRoleService(iRoleRepo)
	roleController := role.NewRoleController(iRoleService)
	return roleController, nil
}

// Injectors from upload.wire.go:

func InitUploadRouterHandler() (*upload.UploadController, error) {
	iUploadService := upload.NewUploadService()
	uploadController := upload.NewUploadController(iUploadService)
	return uploadController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler() (*user.UserController, error) {
	iUserRepo := user.NewUserRepo()
	iRoleRepo := role.NewRoleRepo()
	userIRoleRepo := provideUserRoleRepo(iRoleRepo)
	iConnectionRepo := conection.NewConnectionRepo()
	iConnectionService := provideUserConnectionService(iConnectionRepo)
	iUserService := user.NewUserService(iUserRepo, userIRoleRepo, iConnectionService)
	userController := user.NewUserController(iUserService)
	return userController, nil
}

// Injectors from websocket.wire.go:

func InitWebSocketHandler() (*websocket.Handler, error) {
	hub := websocket.NewHub()
	handler := websocket.NewHandler(hub)
	return handler, nil
}
