version: '3.8'

services:
  redis:
    image: redis:8-alpine
    container_name: go-app-redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command:
      - sh
      - -c
      - |
        exec redis-server \
          --appendonly yes \
          --appendfsync everysec \
          --requirepass "$${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - go-app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -a \"$${REDIS_PASSWORD}\" ping | grep -q PONG"
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:7.0.34-jammy
    container_name: go-app-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - go-app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --username \"$${MONGO_INITDB_ROOT_USERNAME}\" --password \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase admin --eval \"db.adminCommand('ping').ok\" | grep 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio:latest
    container_name: go-app-minio
    restart: unless-stopped
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - go-app-network

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  minio_data:
    driver: local


