services:
  backend:
    image: ghcr.io/harrydo29/go-app:latest
    container_name: go-app-backend
    restart: unless-stopped

    environment:
      # --- SERVER ---
      SERVER_MODE: ${SERVER_MODE}
      SERVER_PORT: ${SERVER_PORT}

      # --- MONGO ---
      MONGO_URI: ${MONGO_URI}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DBNAME: ${MONGO_DBNAME}

      # --- REDIS ---
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      REDIS_POOL: ${REDIS_POOL}

      # --- MINIO ---
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESSKEY: ${MINIO_ACCESSKEY}
      MINIO_SECRETKEY: ${MINIO_SECRETKEY}
      MINIO_USESSL: ${MINIO_USESSL}

      # --- SECURITY ---
      SECURITY_JWT_ACCESS-SECRET: ${SECURITY_JWT_ACCESS-SECRET}
      SECURITY_JWT_ACCESS-EXPIRATION: ${SECURITY_JWT_ACCESS-EXPIRATION}
      SECURITY_JWT_REFRESH-SECRET: ${SECURITY_JWT_REFRESH-SECRET}
      SECURITY_JWT_REFRESH-EXPIRATION: ${SECURITY_JWT_REFRESH-EXPIRATION}
      SECURITY_JWT_RESET-PASSWORD-SECRET: ${SECURITY_JWT_RESET-PASSWORD-SECRET}
      SECURITY_JWT_RESET-PASSWORD-EXPIRATION: ${SECURITY_JWT_RESET-PASSWORD-EXPIRATION}

      # --- LOG ---
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FILENAME: ${LOG_FILENAME}
      LOG_MAXSIZE: ${LOG_MAXSIZE}
      LOG_MAXBACKUPS: ${LOG_MAXBACKUPS}
      LOG_MAXAGE: ${LOG_MAXAGE}
      LOG_COMPRESS: ${LOG_COMPRESS}

      # --- RATELIMIT ---
      RATELIMIT_LIMIT: ${RATELIMIT_LIMIT}
      RATELIMIT_INTERVAL: ${RATELIMIT_INTERVAL}
      RATELIMIT_BURST: ${RATELIMIT_BURST}

      # --- CORS ---
      CORS_ALLOWORIGINS: ${CORS_ALLOWORIGINS}
    ports:
      - ":8080:8080"

    networks:
      - go-app-network

networks:
  go-app-network:
    external: true
    name: go-app-network